# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IssueTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IssueTracker
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'Alamofire'
  pod 'RxGesture'
  pod 'RxDataSources'
  pod 'MarkdownView'

  target 'IssueTrackerTests' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'NSObject+Rx'
    pod 'Alamofire'
    pod 'RxGesture'
    pod 'RxDataSources'
  end

end
